ChicPhoto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from chic_photo.routing import urlpatterns as rout_urls
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include(rout_urls))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chic_photo/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models
from django.contrib.auth.models import User, PermissionsMixin


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(
            email, password, **extra_fields
        )

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(
            email, password, **extra_fields
        )


class Role(models.Model):
    roleName = models.CharField(max_length=10) #Client, Photographer, Admin

    def __str__(self):
        return self.roleName

class User(AbstractBaseUser, PermissionsMixin):
    username = None
    RoleID = models.ForeignKey('Role', on_delete=models.CASCADE, db_default=1)
    email = models.EmailField(unique=True)
    first_name = models.CharField(
        max_length=150,
        blank=True,
        null=True)
    last_name = models.CharField(
        max_length=150,
        blank=True,
        null=True)

    is_active = models.BooleanField(db_default=True)
    is_staff = models.BooleanField(db_default=False)
    USERNAME_FIELD = 'email'
    objects = UserManager()

    def get_role(self):
        return self.RoleID

class Photographer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    skills = models.TextField(null=True, blank=True)
    schedule = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return self.user.first_name

class PhotoDirectory(models.Model):
    photographer = models.ForeignKey(Photographer, on_delete=models.CASCADE, null=True, blank=True)
    photo = models.ImageField(upload_to='photos/')

    def __str__(self):
        return self.photo.name

class StudioSpace(models.Model):
    spaceName = models.CharField(max_length=20, db_index=True)
    description = models.TextField()
    costPerHour = models.DecimalField(max_digits=10, decimal_places=2)
    availability = models.BooleanField()
    image = models.ImageField(upload_to='studios/', null=True, blank=True)

    def __str__(self):
        return self.spaceName

class Service(models.Model):
    serviceName = models.CharField(max_length=20, db_index=True)
    description = models.TextField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.serviceName

class Order(models.Model):
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    serviceID = models.ForeignKey(Service, on_delete=models.CASCADE, null=True)
    photographerID = models.ForeignKey(Photographer, on_delete=models.CASCADE)
    spaceID = models.ForeignKey(StudioSpace, on_delete=models.CASCADE)
    scheduledDate = models.DateField()
    timeFrom = models.TimeField()
    timeTo = models.TimeField()
    active = models.BooleanField(db_default=True)
    totalCost = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Order #{self.id} - {self.userID.first_name + " " + self.userID.last_name}"

chic_photo/forms.py
from bootstrap_datepicker_plus.widgets import DatePickerInput, TimePickerInput
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.db.models import Q
from .models import Order, Photographer, User, PhotoDirectory


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['photographerID', 'spaceID','serviceID', 'scheduledDate', 'timeFrom', 'timeTo']
        widgets = {
            'photographerID': forms.Select(attrs={'class': 'form-select'}),
            'serviceID': forms.Select(attrs={'class': 'form-select'}),
            'spaceID': forms.Select(attrs={'class': 'form-select'}),
            'scheduledDate': DatePickerInput(),
            'timeFrom': TimePickerInput(),
            'timeTo': TimePickerInput(),
        }

    def clean_scheduledDate(self):
        scheduled_date = self.cleaned_data.get('scheduledDate')
        if scheduled_date < timezone.now().date():
            raise forms.ValidationError("")
        elif scheduled_date > timezone.now().date() + timezone.timedelta(days=14):
            raise forms.ValidationError("The date cannot be later than 14 days from the current date")
        return scheduled_date

    def clean(self):
        cleaned_data = super().clean()
        time_from = cleaned_data.get('timeFrom')
        time_to = cleaned_data.get('timeTo')
        if time_from and time_to:
            if time_from.hour < 8 or time_to.hour > 19:
                raise forms.ValidationError("The time should be between 8 a.m. and 7 p.m.")
            if time_from >= time_to:
                raise forms.ValidationError("The start time must be earlier than the end time")

        space_id = cleaned_data.get('spaceID')
        scheduled_date = cleaned_data.get('scheduledDate')

        # Проверка на перекрывающиеся заказы
        overlapping_orders = Order.objects.filter(
            spaceID=space_id,
            scheduledDate=scheduled_date
        ).filter(
            Q(timeFrom__lte=time_from, timeTo__gte=time_to) |  # Новый заказ полностью перекрывает существующий
            Q(timeFrom__lte=time_from, timeTo__gte=time_to) |  # Новый заказ полностью входит в существующий
            Q(timeFrom__lte=time_from, timeTo__lte=time_to, timeTo__gt=time_from) |  # Начало нового заказа внутри существующего
            Q(timeFrom__gte=time_from, timeTo__gte=time_to, timeFrom__lt=time_to)
            # Конец нового заказа внутри существующего
        ).exclude(id=self.instance.id if self.instance else None)

        if overlapping_orders.exists():
            raise ValidationError(
                "There is already an order for this place at this time."
            )

        return cleaned_data


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

class PhotographerForm(forms.ModelForm):
    # Define a new field for photo upload
    new_photo = forms.ImageField(required=False, label='Upload Photo')

    class Meta:
        model = Photographer
        fields = ['skills', 'schedule']
        widgets = {
            'skills': forms.Textarea(attrs={'class': 'form-control'}),
            'schedule': forms.TextInput(attrs={'class': 'form-control'}),
        }


class PortfolioForm(forms.ModelForm):
    class Meta:
        model = PhotoDirectory
        fields = ['photo', 'photographer']

chic_photo/views.py
from datetime import datetime, date
from decimal import Decimal

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView

from ChicPhoto import settings
from chic_photo.forms import OrderForm, UserForm, PhotographerForm, PortfolioForm
from chic_photo.models import User, StudioSpace, Photographer, Order, PhotoDirectory


# Create your views here.

def user_form_view(request):
    user_instance = User.objects.get(pk=request.user.pk)  # Получаем текущего пользователя

    if request.method == 'POST':
        form = UserForm(request.POST, instance=user_instance)
        if form.is_valid():
            form.save()
            return redirect('profile')  # Замените 'success_url' на URL страницы после успешной отправки формы
    else:
        form = UserForm(instance=user_instance)
    return render(request, 'includes/profile_form.html', {'form': form})


def photographer_form_view(request):
    photographer_instance = Photographer.objects.get(user=request.user)

    if request.method == 'POST':
        form = PhotographerForm(request.POST, instance=photographer_instance)
        portfolio_form = PortfolioForm(request.POST, request.FILES)
        if form.is_valid() and portfolio_form.is_valid():
            form.save()
            portfolio = portfolio_form.save(commit=False)
            portfolio.photographer = photographer_instance
            portfolio.save()
            return redirect('profile')  # Перенаправляем на профиль при успешной отправке формы
        else:
            print(form.errors)  # Выводим ошибки формы PhotographerForm
            print(portfolio_form.errors)  # Выводим ошибки формы PortfolioForm
    else:
        form = PhotographerForm(instance=photographer_instance)
        portfolio_form = PortfolioForm()

    return render(request, 'includes/photographer.html', {'form': form, 'portfolio_form': portfolio_form})

def index(request):
    return render(request, 'index.html')

class LoginView(View):
    def get(self, request):
        return render(request, 'authentication/login.html')

    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            return JsonResponse({'message': 'Неверные учетные данные'}, status=401)

class RegistrationView(View):
    def get(self, request):
        return render(request, 'authentication/reg.html')
    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')
        if User.objects.filter(email=email).exists():
            return JsonResponse({'message': 'Пользователь с таким email уже существует'}, status=400)
        user = User.objects.create_user(email=email, password=password)
        login(request, user)
        return redirect('index')

class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
        return redirect('index')

@login_required
def profile(request):
    user = request.user
    role = user.get_role()
    return render(request, 'profile.html', {'user': user, 'role': role,})


def order_form(request):
    pass


def profile_form(request):
    return None
def studiospaces(request):
    return None
class StudioSpaceList(ListView):
    model = StudioSpace
    template_name = 'spaces.html'
    context_object_name = 'list_studios'
    extra_context = {'title': 'Студии'}

@login_required
def get_order_form(request):
    if request.method == 'GET':
        # Создаем форму OrderForm
        form = OrderForm()
        # Возвращаем HTML-код формы в формате JSON
        form_html = render(request, 'includes/order_form.html', {'form': form})
        return form_html
    elif request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():

            order = form.save(commit=False)
            order.userID = request.user
            scheduled_date = datetime.strptime(request.POST['scheduledDate'], '%Y-%m-%d').date()
            time_from = datetime.strptime(request.POST['timeFrom'], '%H:%M').time()
            time_to = datetime.strptime(request.POST['timeTo'], '%H:%M').time()

            order_time_from = datetime.combine(scheduled_date, time_from)
            order_time_to = datetime.combine(scheduled_date, time_to)

            time_difference = (order_time_to - order_time_from).total_seconds() / 3600
            time_difference_decimal = Decimal(str(time_difference))

            total_cost = time_difference_decimal * (
                        Decimal(order.serviceID.cost) + Decimal(order.spaceID.costPerHour))
            order.totalCost = total_cost

            # Устанавливаем идентификатор аутентифицированного пользователя как userId


            order.save()
            return redirect('index')
        else:
            errors = dict([(field, [error for error in errors]) for field, errors in form.errors.items()])
            return JsonResponse({'success': False, 'errors': errors})
class Photographers(ListView):
    model = Photographer
    template_name = 'photographers.html'
    context_object_name = 'photographers'


def order_status(request):
    return None
def generate_invoice(request, order_id):
    try:
        order = Order.objects.get(id=order_id)
    except Order.DoesNotExist:
        return HttpResponse("Order not found.")

    # Создание текстового файла для чека
    invoice_content = f"Чек для заказа #{order_id}\n\n"
    invoice_content += f"Пользователь: {order.userID.first_name} {order.userID.last_name}\n"
    invoice_content += f"Услуга: {order.serviceID.serviceName}\n"
    invoice_content += f"Фотограф: {order.photographerID.user.first_name} {order.photographerID.user.last_name}\n"
    invoice_content += f"Место: {order.spaceID.spaceName}\n"
    invoice_content += f"Дата: {order.scheduledDate}\n"
    invoice_content += f"Время с: {order.timeFrom} до {order.timeTo}\n"
    invoice_content += f"Общая стоимость: {order.totalCost}\n"

    # Путь к файлу
    file_path = f"{settings.BASE_DIR}/chic_photo/invoices/{order_id}.txt"

    # Запись содержимого чека в файл
    with open(file_path, 'w', encoding='utf-8') as invoice_file:
        invoice_file.write(invoice_content)

    return HttpResponse("Invoice generated successfully.")
def orders(request):
    if request.user.RoleID.id == 2:
        all_orders = Order.objects.filter(userID=request.user.id, active=True)
        today_orders = all_orders.filter(scheduledDate=date.today(), userID=request.user.id, active=True)

    elif request.user.RoleID.id == 3:
        all_orders = Order.objects.all()
        today_orders = Order.objects.filter(scheduledDate=date.today())

    elif request.user.RoleID.id == 1:
        all_orders = Order.objects.filter(userID=request.user.id, active=True)
        today_orders = Order.objects.filter(scheduledDate=date.today(), userID=request.user.id, active=True)

    return render(request, 'orders.html', {'all_orders': all_orders, 'today_orders': today_orders})


@login_required
def cancel_order(request, order_id):
    if request.method == 'POST':
        order = Order.objects.get(id=order_id)
        order.active = False
        order.save()
    return redirect('orders')  # Предполагая, что у вас есть имя URL для всех заказов

chic_photo/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block sublink %}
      <!-- Bootstrap Datepicker Plus CSS -->
    <style>
    .main-photo {
      width: 100%;
      height: auto;
      max-width: 100%;
      margin-bottom: 20px;
    }
  </style>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.39.0/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet">
{% endblock %}

{% block main %}
 <!-- Кнопка для отправки запроса на сервер и обновления модального окна -->
    <div class="container">
        <div class="row">
            <div class="col-md-12">
              <img src="{% static 'images/img.png' %}" alt="Main Photo" class="main-photo">
            </div>
      </div>
      <div class="row">
            <div class="col-md-12">
              <h1>Welcome to ChicPhoto Studio</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et gravida magna. Curabitur sed nisl non est ullamcorper facilisis. Mauris semper euismod magna, a laoreet elit convallis sed. Sed malesuada arcu vitae neque consectetur, nec blandit lorem pulvinar. Quisque ut tortor justo.</p>
            </div>
      </div>
      <div class="row">
            <div class="col-md-12">
                <img src="{% static 'images/img_1.png' %}" alt="Secondary Photo" class="main-photo">
            </div>
      </div>
        <button id="openModalButton" class="btn btn-primary" hx-get="orders/getorderform/" hx-target="#openModal" hx-swap="innerHTML">Записаться на фотосессию</button>
        <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Информация</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="openModal" class="modal-body">

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет, спасибо</button>
            </div>
          </div>
        </div>
      </div>
    </div>


{% endblock %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap Bundle with Popper -->

    <!-- Bootstrap Datepicker Plus JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- Tempus Dominus Bootstrap 4 Date & Time Picker JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.39.0/js/tempusdominus-bootstrap-4.min.js"></script>

    {% load static %}
    <script src="{% static 'scripts/htmx.min.js' %}"></script>
    <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
    <script>
        document.addEventListener("htmx:afterSwap", function(event) {
            // Проверяем, что обновленный контент содержит элементы, которые нужно инициализировать
            if (event.detail.target.querySelector("#scheduledDate")) {
                $('#scheduledDate').datepicker({
                  format: 'yyyy-mm-dd',
                  startDate: 'today',
                  autoclose: true,
                  todayHighlight: true
                });
            }
            if (event.detail.target.querySelector("#timeFrom")) {
                $('#timeFrom').datetimepicker({
                  format: 'HH:mm',
                  stepping: 60,
                  ignoreReadonly: true,
                  allowInputToggle: false
                });
                $("#timeFrom").on("click", function (e) {
                  $('#timeFrom').datetimepicker('show');
                });
            }
            if (event.detail.target.querySelector("#timeTo")) {
                $('#timeTo').datetimepicker({
                  format: 'HH:mm',
                  stepping: 60,
                  ignoreReadonly: true,
                  allowInputToggle: false
                });
                $("#timeTo").on("click", function (e) {
                  $('#timeTo').datetimepicker('show');
                });
            }
            if (event.detail.target.matches('#openModal')) {
      // Открываем модальное окно с использованием Bootstrap
            const modal = new bootstrap.Modal(document.querySelector('#modal'));
      // при нажатии на кнопку
             modal.show();
    }
    });
    </script>
{% endblock %}

chic_photo/templates/orders.html
{% extends 'base.html' %}


{% block main %}
    <div class="container">
        <h1>All Orders</h1>
        {% if all_orders %}
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>User</th>
                    <th>Service</th>
                    <th>Photographer</th>
                    <th>Studio Space</th>
                    <th>Scheduled Date</th>
                    <th>Time From</th>
                    <th>Time To</th>
                    <th>Total Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for order in all_orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.userID.first_name }} {{ order.userID.last_name }}</td>
                    <td>{{ order.serviceID.serviceName }}</td>
                    <td>{{ order.photographerID.user.first_name }} {{ order.photographerID.user.last_name }}</td>
                    <td>{{ order.spaceID.spaceName }}</td>
                    <td>{{ order.scheduledDate }}</td>
                    <td>{{ order.timeFrom }}</td>
                    <td>{{ order.timeTo }}</td>
                    <td>{{ order.totalCost }}</td>
                    {% if request.user.RoleID.id == 3 %}
                    <td>
                        <a href="{% url 'generate_invoice' order.id %}" class="btn btn-primary">Generate Invoice</a>
                    </td>
                    {% elif request.user.RoleID.id == 1 %}
                        <td>
                            <form action="{% url 'cancel_order' order.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit"  class="btn btn-danger">Отменить запись</button>
                            </form>
                        </td>
                    {% endif %}
                </tr>

                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>Unfortunately, there are no orders.</p>
        {% endif %}

        <h1>Orders for Today</h1>
        {% if today_orders %}
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>User</th>
                    <th>Service</th>
                    <th>Photographer</th>
                    <th>Studio Space</th>
                    <th>Scheduled Date</th>
                    <th>Time From</th>
                    <th>Time To</th>
                    <th>Total Cost</th>
                </tr>
            </thead>
            <tbody>
                {% for order in today_orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.userID.first_name }} {{ order.userID.last_name }}</td>
                    <td>{{ order.serviceID.serviceName }}</td>
                    <td>{{ order.photographerID.user.first_name }} {{ order.photographerID.user.last_name }}</td>
                    <td>{{ order.spaceID.spaceName }}</td>
                    <td>{{ order.scheduledDate }}</td>
                    <td>{{ order.timeFrom }}</td>
                    <td>{{ order.timeTo }}</td>
                    <td>{{ order.totalCost }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>Unfortunately, there are no orders for today.</p>
        {% endif %}
    </div>
{% endblock %}

chic_photo/templates/photographers.html
{% extends 'base.html' %}

{% block sublink %}
     <style>
        /* Увеличение карточек */
        .card {
            margin-bottom: 20px;
            border-radius: 15px; /* Добавим закругление углов */
            min-width: 800px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Добавим тень */
        }

        /* Стилизация кнопок переключения */
        .carousel-control-prev,
        .carousel-control-next {
            width: 5%; /* Уменьшим ширину кнопок */
            background-color: rgba(0, 0, 0, 0.5); /* Цвет фона кнопок */
            border-radius: 25px; /* Закруглим углы */
        }

        .carousel-control-prev-icon,
        .carousel-control-next-icon {
            background-color: white; /* Цвет иконок */
            border-radius: 50%; /* Закругленные иконки */
            border: none;
        }

        /* При наведении меняем цвет фона кнопок */
        .carousel-control-prev:hover,
        .carousel-control-next:hover {
            background-color: rgba(0, 0, 0, 0.8); /* Цвет фона кнопок при наведении */
        }

        /* При наведении меняем цвет иконок */
        .carousel-control-prev-icon:hover,
        .carousel-control-next-icon:hover {
            background-color: black; /* Цвет иконок при наведении */
        }
    </style>
{% endblock %}

{% block main %}
   <div class="container">
   {% for photographer in photographers %}
        <div class="row">
                <div class="container">
                    <div class="card" style="min-width: 100%">
                        <div class="card-body">
                            <h5 class="card-title">{{ photographer.user.first_name }}</h5>
                            <p class="card-text">Skills: {{ photographer.skills }}</p>
                            <p class="card-text">Schedule: {{ photographer.schedule }}</p>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">Photo Gallery</h5>
                            <div id="photoCarousel{{ photographer.id }}" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    {% for photo in photographer.photodirectory_set.all %}
                                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                            <img class="d-block w-100" src="{{ photo.photo.url }}" alt="Photo">
                                        </div>
                                    {% endfor %}
                                </div>

                                <a class="carousel-control-prev" href="#photoCarousel{{ photographer.id }}" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#photoCarousel{{ photographer.id }}" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

chic_photo/templates/profile.html
{% extends 'base.html' %}

{% block sublink %}

{% endblock %}

{% block main %}
    <div class="container">
        <div class="card mt-5">
            <div class="card-body">
                <h2 class="card-title">{{ user.first_name }} {{ user.last_name }}</h2>
                <p class="card-text">Email: {{ user.email }}</p>
                <p class="card-text">Role: {{ role.roleName }}</p>
                {% if role.id == 1 %}
                    <button id="openModalButton" class="btn btn-primary" hx-get="edit_profile/" hx-target="#openModal" hx-swap="innerHTML" >Edit Profile</button>
                    <a class="btn btn-primary" href="{% url 'orders' %}">View Records</a>
                {% elif role.id == 2  %}
                    <a class="btn btn-primary" href="{% url 'orders' %}">View Records</a>
                    <button id="openModalButton" class="btn btn-primary" hx-get="edit_photographer/" hx-target="#openModal" hx-swap="innerHTML">Edit Photographer Profile</button>
                {% elif role.id == 3 %}
                    <a class="btn btn-primary" href="{% url 'orders' %}">View Records</a>
                {% endif %}
                <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Информация</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div id="openModal" class="modal-body">

                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет, спасибо</button>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<!-- Bootstrap JS and dependencies (optional) -->

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap Bundle with Popper -->

    <!-- Bootstrap Datepicker Plus JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- Tempus Dominus Bootstrap 4 Date & Time Picker JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.39.0/js/tempusdominus-bootstrap-4.min.js"></script>

    {% load static %}
    <script src="{% static 'scripts/htmx.min.js' %}"></script>
    <script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
    <script>
        document.addEventListener("htmx:afterSwap", function(event) {
            if (event.detail.target.matches('#openModal')) {
      // Открываем модальное окно с использованием Bootstrap
            const modal = new bootstrap.Modal(document.querySelector('#modal'));
      // при нажатии на кнопку
             modal.show();
    }
    });
    </script>
{% endblock %}